package familycommandcenter.model;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * POJO that mirrors a row in the <code>users</code> table.
 * <p>
 * Most fields are effectively immutable after construction; only a few
 * (id, role, age, passwordHash) expose mutators for the handful of cases
 * where the value may legitimately change.
 */
public class User {

    /* ───── persisted columns ───── */
    private int id; // PK – generated by DB
    private final String username;
    private String passwordHash; // hashed PIN
    private final LocalDateTime createdAt;
    private int age;
    private String role; // "parent" | "kid"
    private final UUID householdId; // FK to household

    /* ───────── constructor ───────── */
    public User(int id,
            String username,
            String passwordHash,
            LocalDateTime createdAt,
            int age,
            String role,
            UUID householdId) {

        this.id = id;
        this.username = username;
        this.passwordHash = passwordHash;
        this.createdAt = createdAt;
        this.age = age;
        this.role = role;
        this.householdId = householdId;
    }

    /* ───────── getters ───────── */
    public int getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public int getAge() {
        return age;
    }

    public String getRole() {
        return role;
    }

    public UUID getHouseholdId() {
        return householdId;
    } // ★ correct camel-case

    /* ───────── controlled mutators ───────── */
    public void setId(int id) {
        this.id = id;
    }

    public void setPasswordHash(String hash) {
        this.passwordHash = hash;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setRole(String role) {
        this.role = role;
    }
}
